---
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.4
  ms-teams-notifier: oktapodia/ms-teams-notifier@1.0.0

jobs:
  checkout:
    docker:
      - image: cimg/node:16.8.0

    steps:
      - checkout
      - persist_to_workspace:
          root: ~/project
          paths: [.]

  test:
    docker:
      - image: cimg/node:16.8.0
    resource_class: small

    steps:
      - add_ssh_keys:
          fingerprints:
            # for write access to github
            # got to the project -> Project Settings -> SSH Keys -> Add User Key
            # add the fingerprint here
            - "d0:85:60:27:a0:8c:e8:95:45:bd:c2:d2:47:7c:f3:b1"

      - attach_workspace:
          at: ~/project
      - run:
          name: Copy ssh config
          command: |
            mkdir ~/.ssh/
            cp .circleci/ssh_config ~/.ssh/config
      - run:
          name: install dependencies
          command: yarn

      - run:
          name: Run tests ...
          command: echo "should run tests"

      - persist_to_workspace:
          root: .
          paths: [./*/]

      - store_artifacts:
          path: ./coverage
          destination: coverage

      #- store_test_results:
      #    path: Results/xunit.xml

      - ms-teams-notifier/report:
          webhook_url: $MS_TEAMS_WEBHOOK_URL

workflows:
  version: 2

  test:
    jobs:
      - checkout:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - checkout

          context:
            - test-automation-qa
          filters:
            tags:
              only: /.*/
            branches:
              only:
                #- main
                -  feature/integration-test-libs
