---
version: 2.1

orbs:
  ms-teams-notifier: oktapodia/ms-teams-notifier@1.0.0
  node: circleci/node@5.1.0

executors:
  node:
    docker:
      - image: cimg/node:18.0.0

jobs:
  test:
    executor: node
    resource_class: small
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn run test:ci
      - persist_to_workspace:
          root: .
          paths: [./*/]
      - store_artifacts:
          path: ./coverage
          destination: coverage/
      - store_test_results:
          path: ./coverage/unit/xunit.xml
      - ms-teams-notifier/report:
          webhook_url: $MS_TEAMS_WEBHOOK_URL

workflows:
  test:
    jobs:
      - test:
          requires:
            - checkout
          context:
            - test-automation-qa
          filters:
            tags:
              only: /.*/
